parameters:
    database_driver:   pdo_mysql
    database_host:     mysql.daviddurost.net
    database_port:     ~
    database_name:     dd_trails2
    database_user:     ner0tic
    database_password: gatorade

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            4IN1N0M1NHI6H3N0U6H
