hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
user_security:
    resource: "@LandmarxUserBundle/Resources/config/routing/security.yml"
user_signup:
    resource: "@LandmarxUserBundle/Resources/config/routing/signup.yml"
    prefix: /signup
category:
    resource: "@LandmarxLandmarkBundle/Resources/config/routing/landmark_category.yml"
    prefix: /
details:
    resource: "@LandmarxLandmarkBundle/Resources/config/routing/landmark_details.yml"
    prefix: /
landmark:
    resource: "@LandmarxLandmarkBundle/Resources/config/routing/landmark.yml"
    prefix: /
collection:
    resource: "@LandmarxLandmarkCollectionBundle/Resources/config/routing/landmark_collection.yml"
    prefix: /
    
################################################################################
# retaining OG routes but are now managed in seperate files listed above       #
################################################################################
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
# 
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
homepage:
    pattern: /
    defaults: { _controller: LandmarxUserBundle:User:index }
account_settings:
    pattern: /my-account
    defaults: { _controller: LandmarxUserBundle:User:settings }