security:
    acl:
        connection: default
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    providers:
        fos_userbundle:
            id: fos_user.user_manager
    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /signin-check
                login_path: /signin
            logout:       true # handlers: ["fos_facebook.logout_handler"]
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~
            fos_facebook:
                app_url: "http://apps.facebook.com/scss/"
                server_url: "http://landmarx.daviddurost.net/facebookApp/"
            oauth:
                resource_owners:
                    google:   "/signin/google/check"
                    facebook: "/signin/facebook/check"
                login_path: /connect
                failure_path: /connect
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge
    access_control:
        - { path: ^/sigin$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/signup, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: [ ROLE_USER, IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_ANONYMOUSLY] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN