categories:
    pattern: /landmarks
    defaults: { _controller: LandmarxLandmarkBundle:LandmarkCategory:index }
category_show:
    pattern: /landmarks/categories/{slug}
    defaults: { _controller: LandmarxLandmarkBundle:LandmarkCategory:show }
category_add:
    pattern: /landmarks/categories/add
    defaults: { _controller: LandmarxLandmarkBundle:LandmarkCategory:new }
category_edit:
    pattern: /landmarks/categories/{slug}/edit
    defaults: { _controller: LandmarxLandmarkBundle:LandmarkCategory:edit }